

comment: false

coverage:
  status:
    project:
      default:
        # Commits pushed to main should not make the overall
        # project coverage decrease by more than 5%:
        target: auto
        threshold: 5%
    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note: The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        target: auto
        threshold: 5%

codecov:
  notify:
    after_n_builds: 1

ignore:
- "tests"
- "src/streamlit_helper.py"
- "src/app.py"
