[tool.poetry]
name = "symbaroum-adventures"
version = "0.1.0"
description = ""
authors = ["sven stehle <svenstehle@web.de>"]

[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
