attribute_names_ger: ["Aufmerksamkeit", "Ausstrahlung", "Gewandtheit", "Heimlichkeit", "Präzision", "Scharfsinn", "Stärke", "Willenskraft"]
attribute_names_eng: ["ACC", "CUN", "DIS", "PER", "QUI", "RES", "STR", "VIG"]
