####
# OCRConfig
####

image: images/draghul.png
save_path: runs
supported_image_types: ["png", "jpg", "jpeg", "webp"]
attribute_names: ["Aufmerksamkeit", "Ausstrahlung", "Gewandtheit", "Heimlichkeit", "Präzision", "Scharfsinn", "Stärke", "Willenskraft"]
psm: 4
oem: 3
