####
# OCRConfig
####

image: images/hunter.tiff
# image: images/draghul.tiff
save_path: runs
supported_image_types: ["png", "tiff"]
attribute_names_ger: ["Aufmerksamkeit", "Ausstrahlung", "Gewandtheit", "Heimlichkeit", "Präzision", "Scharfsinn", "Stärke", "Willenskraft"]
attribute_names_eng: ["ACC", "CUN", "DIS", "PER", "QUI", "RES", "STR", "VIG"]
debug_psm: 4 # for adventure and core rulebook book character sheets alike, sometimes 6
oem: 1
debug_lang: eng
