# This workflow will install Python dependencies, run tests with a variety of Python and OS versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEBUG: true

jobs:
  test:
    runs-on: ${{ matrix.system.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]
        system: [
          {
            os: "ubuntu-latest",
            prod: ".github/scripts/ubuntu_prod.sh",
            debug: ".github/scripts/ubuntu_debug.sh"
          },
          {
            os: "macos-latest",
            prod: ".github/scripts/macos_prod.sh",
            debug: ".github/scripts/macos_debug.sh"
          },
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install System Dependencies Debug
      if: ${{ env.DEBUG == 'true' }}
      run: ${{ matrix.system.debug }}

    - name: Install System Dependencies Prod
      if: ${{ env.DEBUG == 'false' }}
      run: ${{ matrix.system.prod }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create true
        poetry install

    - name: Install chromedriver
      run: |
        poetry run seleniumbase install chromedriver latest
        poetry run sbase install chromedriver latest

    - name: Start Streamlit app
      run: |
        nohup poetry run streamlit run src/app.py &

    - name: Sleep for 8 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '8s'

    - name: Testing the Code with Pytest
      run: PYTHONPATH=./src poetry run pytest tests/unit/ocr --cov-report=xml --cov

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml,./coverage.xml
        fail_ci_if_error: false
