# This workflow will install Python dependencies, run tests with a variety of Python and OS versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.system.os }}
    strategy:
      fail-fast: false
      matrix:
        system: [
          {os: "ubuntu-latest", cmd: "sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-deu"},
          {os: "macos-latest", cmd: "brew install tesseract-lang"}
        ]
        python-version: ["3.8", "3.9"]

    steps:
    - name: Install System Dependencies
      run: ${{ matrix.system.cmd }}

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver latest
        sbase install chromedriver latest

    - name: Start Streamlit app
      run: |
        nohup poetry run streamlit run src/app.py &

    - name: Testing the Code with Pytest
      run: PYTHONPATH=./src poetry run pytest --cov-report=xml --cov

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml,./coverage.xml
        fail_ci_if_error: false
